### Importing Numpy and Pandas

In [3]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.16.2'

In [3]:
pd.__version__

'0.24.2'

#### 1 Dimensionanl Array

In [4]:
#List
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [5]:
#Array
_1D = np.array(my_list)
_1D

array([1, 2, 3, 4])

#### 2 Dimensional Array

In [6]:
my_list2 = [[1,2,3],[4,5,6],[7,8,9]]
my_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
_2D = np.array(my_list2)
_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Generate random numbers

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

#### Generate zeros

In [11]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Generate ones

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Generate any number

In [14]:
np.ones((5,5)) * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

#### Generate equally spaced numbers

In [15]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

#### Generate identity matrix

In [16]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

#### Generate random values

In [17]:
np.random.rand(10)

array([0.75624206, 0.10912326, 0.60071481, 0.59346148, 0.03575435,
       0.57574791, 0.30494583, 0.02948025, 0.88477591, 0.11737236])

In [18]:
np.random.randint(0,50,10)

array([27, 24, 19, 32, 35, 31,  5, 44, 19, 45])

In [19]:
my_arr = np.random.randint(0,30,50)
my_arr

array([10, 13, 28, 28,  3, 28, 11,  4, 24,  2, 23, 12,  0,  9, 28, 27, 10,
        4, 23, 22, 18, 17, 12,  0,  8, 16,  4, 28,  5, 17,  2, 12, 20, 22,
       20,  8, 16,  7, 28, 21, 19, 14,  1, 17, 28, 12, 23, 25, 23,  0])

In [20]:
print(np.max(my_arr))
print(my_arr.max())
print(np.min(my_arr))
print(my_arr.min())

28
28
0
0


#### Shape

In [21]:
my_arr.shape

(50,)

#### Reshape

In [22]:
my_arr.reshape(10,5)

array([[10, 13, 28, 28,  3],
       [28, 11,  4, 24,  2],
       [23, 12,  0,  9, 28],
       [27, 10,  4, 23, 22],
       [18, 17, 12,  0,  8],
       [16,  4, 28,  5, 17],
       [ 2, 12, 20, 22, 20],
       [ 8, 16,  7, 28, 21],
       [19, 14,  1, 17, 28],
       [12, 23, 25, 23,  0]])

In [23]:
my_arr.dtype

dtype('int32')

#### Arithmetic Operation

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Addition

In [25]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
arr + 11

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [27]:
arr[::2] + 50

array([50, 52, 54, 56, 58, 60])

#### Subtraction

In [28]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
arr - 11

array([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [30]:
arr[1::2] - 50

array([-49, -47, -45, -43, -41])

#### Multiplication

In [31]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
arr *15

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150])

In [5]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

#### Division

In [34]:
arr/arr

C:\Users\zalego\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
arr/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333])

#### Max

In [36]:
np.max(arr)

10

#### Min

In [37]:
np.min(arr)

0

#### Log

In [38]:
np.log(arr)

C:\Users\zalego\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#### Sin

In [39]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

#### Tan

In [40]:
np.tan(arr)


array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

#### Cos

In [41]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

#### Exponent

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

### Slicing

In [44]:
arr1 = np.arange(11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr1[0:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [71]:
arr2 = np.random.randint(0,20,20)
arr2

array([17,  7,  3,  8,  8, 17,  1,  1, 15, 18,  7,  4,  4,  5, 19, 13,  7,
       11, 13, 12])

In [72]:
arr3 = arr2.reshape(4,5)
arr3

array([[17,  7,  3,  8,  8],
       [17,  1,  1, 15, 18],
       [ 7,  4,  4,  5, 19],
       [13,  7, 11, 13, 12]])

In [73]:
arr3[1]

array([17,  1,  1, 15, 18])

In [74]:
arr3[1][2]

1

In [75]:
arr3[3][4]

12

In [77]:
arr3[-4][-5]

17